<thead>
    <tr>
        <td><a href="{{ Request::url() }}?view={{ Request::input('view') }}&sort=id.{{$sorter == 'id' && $direction == 'asc' ? 'desc' : 'asc' }}" style="text-decoration:none"><i class="fa fa-sort{{ $sorter == 'id' ? '-'.$dirIcon : '' }}" aria-hidden="true"></i> ID </a></td>
        <td><a href="{{ Request::url() }}?view={{ Request::input('view') }}&sort=date.{{$sorter == 'date' && $direction == 'asc' ? 'desc' : 'asc' }}" style="text-decoration:none"><i class="fa fa-sort{{ $sorter == 'date' ? '-'.$dirIcon : '' }}" aria-hidden="true"></i> Date</a></td>
        <td><a href="{{ Request::url() }}?view={{ Request::input('view') }}&sort=type.{{$sorter == 'type' && $direction == 'asc' ? 'desc' : 'asc' }}" style="text-decoration:none"><i class="fa fa-sort{{ $sorter == 'type' ? '-'.$dirIcon : '' }}" aria-hidden="true"></i> Services Type </a></td>
        <td><a href="{{ Request::url() }}?view={{ Request::input('view') }}&sort=cat_id.{{$sorter == 'cat_id' && $direction == 'asc' ? 'desc' : 'asc' }}" style="text-decoration:none"><i class="fa fa-sort{{ $sorter == 'cat_id' ? '-'.$dirIcon : '' }}" aria-hidden="true"></i> Services Category </a></td>
        <td><a href="{{ Request::url() }}?view={{ Request::input('view') }}&sort=sub_cat_id.{{$sorter == 'sub_cat_id' && $direction == 'asc' ? 'desc' : 'asc' }}" style="text-decoration:none"><i class="fa fa-sort{{ $sorter == 'sub_cat_id' ? '-'.$dirIcon : '' }}" aria-hidden="true"></i> Services Sub Category</a></td>
        <td><a href="{{ Request::url() }}?view={{ Request::input('view') }}&sort=response_time.{{$sorter == 'response_time' && $direction == 'asc' ? 'desc' : 'asc' }}" style="text-decoration:none"><i class="fa fa-sort{{ $sorter == 'response_time' ? '-'.$dirIcon : '' }}" aria-hidden="true"></i> Response Time (HH:MM)</a></td>
        <td><a href="{{ Request::url() }}?view={{ Request::input('view') }}&sort=assessment_time.{{$sorter == 'assessment_time' && $direction == 'asc' ? 'desc' : 'asc' }}" style="text-decoration:none"><i class="fa fa-sort{{ $sorter == 'assessment_time' ? '-'.$dirIcon : '' }}" aria-hidden="true"></i> Assessment Time (HH:MM)</a></td>
        <td><a href="{{ Request::url() }}?view={{ Request::input('view') }}&sort=rectification_time.{{$sorter == 'rectification_time' && $direction == 'asc' ? 'desc' : 'asc' }}" style="text-decoration:none"><i class="fa fa-sort{{ $sorter == 'rectification_time' ? '-'.$dirIcon : '' }}" aria-hidden="true"></i> Rectification Time (HH:MM)</a></td>
        <td><a href="{{ Request::url() }}?view={{ Request::input('view') }}&sort=breach_response_time.{{$sorter == 'breach_response_time' && $direction == 'asc' ? 'desc' : 'asc' }}" style="text-decoration:none"><i class="fa fa-sort{{ $sorter == 'breach_response_time' ? '-'.$dirIcon : '' }}" aria-hidden="true"></i> Breach Response Time</a></td>
        <td><a href="{{ Request::url() }}?view={{ Request::input('view') }}&sort=breach_assessment_time.{{$sorter == 'breach_assessment_time' && $direction == 'asc' ? 'desc' : 'asc' }}" style="text-decoration:none"><i class="fa fa-sort{{ $sorter == 'breach_assessment_time' ? '-'.$dirIcon : '' }}" aria-hidden="true"></i> Breach Assessment Time</a></td>
        <td><a href="{{ Request::url() }}?view={{ Request::input('view') }}&sort=breach_rectification_time.{{$sorter == 'breach_rectification_time' && $direction == 'asc' ? 'desc' : 'asc' }}" style="text-decoration:none"><i class="fa fa-sort{{ $sorter == 'breach_rectification_time' ? '-'.$dirIcon : '' }}" aria-hidden="true"></i> Breach Rectification Time</a></td>
        <td > Operations </td>
    </tr>
    </thead>
